import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";

const C=window.GREENE_CONFIG||{}, configured=C.SUPABASE_URL?.startsWith("https://")&&!C.SUPABASE_ANON_KEY?.startsWith("COLE_");
const sb=configured?createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY):null;
const views=[["dashboard","⌂","Dashboard"],["daily","◷","Diário"],["sleep","☾","Sono"],["habits","✓","Hábitos"],["books","▤","Leituras"],["studies","✦","Estudos"],["goals","◎","Objetivos"],["analysis","⌁","Análises"]];
let state={view:"dashboard",user:null,daily:[],sleep:[],books:[],studies:[],goals:[]};
const $=s=>document.querySelector(s), esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const today=()=>new Date().toISOString().slice(0,10), avg=a=>a.length?(a.reduce((x,y)=>x+(+y||0),0)/a.length).toFixed(1):"—";
const toast=m=>{let x=$("#toast");x.textContent=m;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1600)};
$("#dateLabel").textContent=new Date().toLocaleDateString("pt-BR",{weekday:"long",day:"numeric",month:"long"});
$("#nav").innerHTML=views.map(([v,i,t])=>`<button class="nav" data-go="${v}">${i} <span class="txt">${t}</span></button>`).join("");

document.addEventListener("click",async e=>{
 const go=e.target.closest("[data-go]")?.dataset.go;if(go){state.view=go;render()}
 const rate=e.target.closest("[data-rate]");if(rate){const n=rate.dataset.rate;document.querySelectorAll(`[data-rate="${n}"]`).forEach(x=>x.classList.remove("on"));rate.classList.add("on");document.querySelector(`[name="${n}"]`).value=rate.dataset.val}
 const del=e.target.closest("[data-del]");if(del){await remove(del.dataset.del,del.dataset.id)}
});
$("#authForm").addEventListener("submit",async e=>{e.preventDefault();if(!sb)return msg("Configure o Supabase primeiro.");const {error}=await sb.auth.signInWithPassword({email:$("#email").value,password:$("#password").value});if(error)msg(error.message)});
$("#signupBtn").addEventListener("click",async()=>{if(!sb)return msg("Configure o Supabase primeiro.");const {error}=await sb.auth.signUp({email:$("#email").value,password:$("#password").value});msg(error?error.message:"Conta criada. Se a confirmação de e-mail estiver ativa, confirme seu e-mail.")});
$("#logoutBtn").addEventListener("click",()=>sb?.auth.signOut());
$("#exportBtn").addEventListener("click",()=>{const b=new Blob([JSON.stringify({...state,user:undefined},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=`greene-${today()}.json`;a.click();URL.revokeObjectURL(a.href)});
function msg(x){$("#authMsg").textContent=x}
if(!configured){$("#authMsg").innerHTML='Primeiro configure <b>config.js</b> com a URL e a chave pública do Supabase.'}
if(sb){sb.auth.onAuthStateChange(async(_,session)=>{state.user=session?.user||null;$("#auth").classList.toggle("hidden",!!state.user);$("#shell").classList.toggle("hidden",!state.user);if(state.user){await loadAll();render()}});const {data:{session}}=await sb.auth.getSession();if(session){state.user=session.user;$("#auth").classList.add("hidden");$("#shell").classList.remove("hidden");await loadAll();render()}}

async function loadAll(){for(const t of ["daily_entries","sleep_entries","books","studies","goals"]){const {data,error}=await sb.from(t).select("*").order(t==="books"?"created_at":"date",{ascending:false});if(!error)state[{daily_entries:"daily",sleep_entries:"sleep",books:"books",studies:"studies",goals:"goals"}[t]]=data||[]}}
async function upsert(table,obj){const {error}=await sb.from(table).upsert({...obj,user_id:state.user.id},{onConflict:"user_id,date"});if(error)toast(error.message);else{toast("Salvo");await loadAll();state.view="dashboard";render()}}
async function insert(table,obj){const {error}=await sb.from(table).insert({...obj,user_id:state.user.id});if(error)toast(error.message);else{toast("Salvo");await loadAll();render()}}
async function remove(table,id){const {error}=await sb.from(table).delete().eq("id",id);if(error)toast(error.message);else{await loadAll();render()}}
function rating(n,v=3){return `<input type="hidden" name="${n}" value="${v}"><div class="rating">${[1,2,3,4,5].map(x=>`<button type="button" data-rate="${n}" data-val="${x}" class="${+v===x?"on":""}">${x}</button>`).join("")}</div>`}
function sleepHours(x){if(!x?.bed_time||!x?.wake_time)return 0;let [a,b]=x.bed_time.split(":").map(Number),[c,d]=x.wake_time.split(":").map(Number),m=(c*60+d)-(a*60+b);if(m<=0)m+=1440;return m/60}
function render(){const names=Object.fromEntries(views.map(x=>[x[0],x[2]]));$("#title").textContent=names[state.view];document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.go===state.view));$("#content").innerHTML=({dashboard,daily,sleep,habits,books,studies,goals,analysis}[state.view])();bindForms()}
function dashboard(){let d=state.daily.slice(0,7),s=state.sleep.slice(0,7);return `<div class="grid stats"><div class="card"><span class="muted small">Sono médio</span><div class="metric">${s.length?avg(s.map(sleepHours))+"h":"—"}</div></div><div class="card"><span class="muted small">Energia</span><div class="metric">${d.length?avg(d.map(x=>x.energy))+"/5":"—"}</div></div><div class="card"><span class="muted small">Foco</span><div class="metric">${d.length?avg(d.map(x=>x.focus))+"/5":"—"}</div></div><div class="card"><span class="muted small">Livros</span><div class="metric">${state.books.length}</div></div></div><div class="grid two" style="margin-top:15px"><div class="card"><h3>Hoje</h3><p class="muted">${state.daily.some(x=>x.date===today())?"Registro preenchido.":"Seu registro diário ainda está vazio."}</p><button class="primary" data-go="daily">Registrar hoje</button></div><div class="card"><h3>Sincronização</h3><p class="muted">Seus registros desta conta ficam no Supabase e aparecem nos dispositivos em que você entrar.</p></div></div>`}
function daily(){let d=state.daily.find(x=>x.date===today())||{};return `<div class="card"><h3>Check-in de hoje</h3><p class="muted small">O essencial em cerca de 2 minutos.</p><form data-form="daily"><div class="form-grid">${[["energy","Energia"],["mood","Humor"],["stress","Estresse"],["focus","Foco"]].map(([n,l])=>`<div class="field"><label>${l} · 1 a 5</label>${rating(n,d[n]||3)}</div>`).join("")}<div class="field full"><label>Hábitos</label><div class="grid two">${[["exercise","Exercício"],["reading","Leitura"],["study","Estudo"],["water","Água"],["organization","Organização"],["social_control","Redes sociais sob controle"]].map(([n,l])=>`<label><input type="checkbox" name="${n}" ${d[n]?"checked":""}> ${l}</label>`).join("")}</div></div><div class="field full"><label>O que marcou seu dia?</label><textarea name="notes" rows="4">${esc(d.notes)}</textarea></div></div><div class="actions"><button class="primary">Salvar</button></div></form></div>`}
function sleep(){let d=state.sleep.find(x=>x.date===today())||{};return `<div class="card"><h3>Registrar sono</h3><form data-form="sleep"><div class="form-grid"><div class="field"><label>Data</label><input name="date" type="date" value="${d.date||today()}" required></div><div class="field"><label>Dormi às</label><input name="bed_time" type="time" value="${d.bed_time||""}" required></div><div class="field"><label>Acordei às</label><input name="wake_time" type="time" value="${d.wake_time||""}" required></div><div class="field"><label>Despertares</label><input name="awakenings" type="number" min="0" value="${d.awakenings||0}"></div><div class="field"><label>Qualidade · 1 a 5</label>${rating("quality",d.quality||3)}</div><div class="field full"><label>Observações</label><textarea name="notes" rows="3">${esc(d.notes)}</textarea></div></div><div class="actions"><button class="primary">Salvar</button></div></form></div>`}
function habits(){let keys=[["exercise","Exercício"],["reading","Leitura"],["study","Estudo"],["water","Água"],["organization","Organização"],["social_control","Redes sociais sob controle"]];return `<div class="grid three">${keys.map(([k,n])=>`<div class="card"><h3>${n}</h3><div class="metric">${state.daily.filter(x=>x[k]).length}</div><span class="muted small">dias concluídos</span></div>`).join("")}</div>`}
function books(){return `<div class="card"><h3>Novo livro</h3><form data-form="book"><div class="form-grid"><div class="field"><label>Título</label><input name="title" required></div><div class="field"><label>Autor</label><input name="author"></div><div class="field"><label>Status</label><select name="status"><option>Quero ler</option><option>Em andamento</option><option>Lido</option></select></div><div class="field"><label>Páginas</label><input name="pages" type="number" min="0"></div><div class="field"><label>Nota</label>${rating("rating",3)}</div><div class="field full"><label>Aprendizado principal</label><textarea name="notes" rows="3"></textarea></div></div><div class="actions"><button class="primary">Adicionar</button></div></form></div><h2 class="section">Biblioteca</h2><div class="list">${state.books.map(b=>`<div class="row"><div><strong>${esc(b.title)}</strong><small class="muted">${esc(b.author)} · ${esc(b.status)} · ${b.rating||"—"}/5</small></div><button class="secondary" data-del="books" data-id="${b.id}">Excluir</button></div>`).join("")||'<div class="empty">Nenhum livro registrado.</div>'}</div>`}
function studies(){return `<div class="card"><h3>Registrar estudo</h3><form data-form="study"><div class="form-grid"><div class="field"><label>Data</label><input name="date" type="date" value="${today()}" required></div><div class="field"><label>Assunto</label><input name="subject" required></div><div class="field"><label>Minutos</label><input name="minutes" type="number" min="1" required></div><div class="field full"><label>O que aprendi?</label><textarea name="learned" rows="3"></textarea></div></div><div class="actions"><button class="primary">Salvar</button></div></form></div><h2 class="section">Histórico</h2><div class="list">${state.studies.map(x=>`<div class="row"><div><strong>${esc(x.subject)}</strong><small class="muted">${x.date} · ${x.minutes} min</small></div><button class="secondary" data-del="studies" data-id="${x.id}">Excluir</button></div>`).join("")||'<div class="empty">Nenhum estudo registrado.</div>'}</div>`}
function goals(){return `<div class="card"><h3>Novo objetivo</h3><form data-form="goal"><div class="form-grid"><div class="field"><label>Objetivo</label><input name="title" required></div><div class="field"><label>Prazo</label><input name="deadline" type="date"></div><div class="field"><label>Progresso (%)</label><input name="progress" type="number" min="0" max="100" value="0"></div></div><div class="actions"><button class="primary">Adicionar</button></div></form></div><h2 class="section">Objetivos</h2><div class="list">${state.goals.map(g=>`<div class="card"><div class="row" style="border:0;padding:0 0 10px"><strong>${esc(g.title)}</strong><button class="secondary" data-del="goals" data-id="${g.id}">Excluir</button></div><small class="muted">${g.deadline?"Prazo: "+g.deadline:"Sem prazo"} · ${g.progress}%</small><div class="progress" style="margin-top:8px"><div style="width:${Math.max(0,Math.min(100,g.progress))}%"></div></div></div>`).join("")||'<div class="empty">Nenhum objetivo registrado.</div>'}</div>`}
function analysis(){return `<div class="grid two">${[["Sono médio",state.sleep.length?avg(state.sleep.slice(0,30).map(sleepHours))+"h":"—"],["Qualidade do sono",state.sleep.length?avg(state.sleep.slice(0,30).map(x=>x.quality))+"/5":"—"],["Energia média",state.daily.length?avg(state.daily.slice(0,30).map(x=>x.energy))+"/5":"—"],["Humor médio",state.daily.length?avg(state.daily.slice(0,30).map(x=>x.mood))+"/5":"—"],["Foco médio",state.daily.length?avg(state.daily.slice(0,30).map(x=>x.focus))+"/5":"—"],["Dias registrados",state.daily.length]].map(x=>`<div class="card"><span class="muted small">${x[0]}</span><div class="metric">${x[1]}</div></div>`).join("")}</div><div class="card" style="margin-top:15px"><h3>Próxima evolução</h3><p class="muted">Com histórico suficiente, adicionaremos gráficos temporais e análises de associação entre sono, energia, foco, humor e hábitos.</p></div>`}
function bindForms(){document.querySelectorAll("form[data-form]").forEach(f=>f.addEventListener("submit",async e=>{e.preventDefault();let x=Object.fromEntries(new FormData(f)),type=f.dataset.form;if(type==="daily"){["exercise","reading","study","water","organization","social_control"].forEach(k=>x[k]=f.elements[k].checked);["energy","mood","stress","focus"].forEach(k=>x[k]=+x[k]);x.date=today();await upsert("daily_entries",x)}if(type==="sleep"){x.quality=+x.quality;x.awakenings=+x.awakenings;await upsert("sleep_entries",x)}if(type==="book"){x.pages=+x.pages||0;x.rating=+x.rating;await insert("books",x)}if(type==="study"){x.minutes=+x.minutes;await insert("studies",x)}if(type==="goal"){x.progress=+x.progress||0;x.date=today();await insert("goals",x)}}))}
if(!state.user && !configured){}