import{createClient}from"https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const C=window.GREENE_CONFIG||{},ok=C.SUPABASE_URL?.startsWith("https://")&&!C.SUPABASE_ANON_KEY?.startsWith("COLE_"),sb=ok?createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY):null,$=s=>document.querySelector(s),today=()=>new Date().toISOString().slice(0,10),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),avg=a=>a.length?(a.reduce((x,y)=>x+(+y||0),0)/a.length).toFixed(1):"—";
let S={user:null,view:"dashboard",daily:[],sleep:[],habits:[],habit_logs:[],books:[],studies:[],goals:[]};
const V=[["dashboard","Dashboard"],["daily","Diário"],["sleep","Sono"],["habits","Hábitos"],["books","Leituras"],["studies","Estudos"],["goals","Objetivos"],["analysis","Análises"]];
$("nav").innerHTML=V.map(x=>`<button class="nav" data-go="${x[0]}">${x[1]}</button>`).join("");$("#date").textContent=new Date().toLocaleDateString("pt-BR",{weekday:"long",day:"numeric",month:"long"});
function toast(m){$("#toast").textContent=m;$("#toast").style.display="block";setTimeout(()=>$("#toast").style.display="none",1800)}
async function load(){for(const [t,k,ord]of[["daily_entries","daily","date"],["sleep_entries","sleep","date"],["habits","habits","created_at"],["habit_logs","habit_logs","date"],["books","books","created_at"],["studies","studies","date"],["goals","goals","date"]]){let{data,error}=await sb.from(t).select("*").order(ord,{ascending:false});if(!error)S[k]=data||[]}}
async function add(t,x){let{error}=await sb.from(t).insert({...x,user_id:S.user.id});if(error)return toast(error.message);await load();render();toast("Salvo")}
async function up(t,x){let{error}=await sb.from(t).upsert({...x,user_id:S.user.id},{onConflict:"user_id,date"});if(error)return toast(error.message);await load();render();toast("Salvo")}
async function del(t,id){if(!confirm("Excluir este registro?"))return;let{error}=await sb.from(t).delete().eq("id",id);if(error)return toast(error.message);await load();render()}
function rate(n,v=3){return`<input type=hidden name="${n}" value="${v}"><div class=ratings>${[1,2,3,4,5].map(i=>`<button type=button data-rate="${n}" data-v="${i}" class="${+v===i?"on":""}">${i}</button>`).join("")}</div>`}
function hours(x){if(!x?.bed_time||!x?.wake_time)return 0;let[a,b]=x.bed_time.split(":").map(Number),[c,d]=x.wake_time.split(":").map(Number),m=c*60+d-a*60-b;return(m<=0?m+1440:m)/60}
function dashboard(){let d=S.daily.slice(0,7),p=S.daily.slice(7,14),sl=S.sleep.slice(0,7),done=S.habit_logs.filter(x=>x.date===today()&&x.completed).length,active=S.habits.filter(x=>x.active).length,ed=d.length&&p.length?(+avg(d.map(x=>x.energy))-(+avg(p.map(x=>x.energy)))).toFixed(1):null;return`<div class="grid stats">${[["Sono · 7 dias",sl.length?avg(sl.map(hours))+"h":"—"],["Energia · 7 dias",d.length?avg(d.map(x=>x.energy))+"/5":"—"],["Foco · 7 dias",d.length?avg(d.map(x=>x.focus))+"/5":"—"],["Hábitos hoje",`${done}/${active}`]].map(x=>`<div class=card><small>${x[0]}</small><div class=metric>${x[1]}</div></div>`).join("")}</div><div class="grid two" style="margin-top:14px"><div class=card><h3>Hoje</h3><p class=muted>${S.daily.some(x=>x.date===today())?"Check-in preenchido.":"Check-in ainda não preenchido."}</p><button data-go=daily>Abrir diário</button></div><div class=card><h3>Tendência</h3><p class=muted>${ed===null?"Precisamos de mais dados para comparar períodos.":`Energia: ${+ed>=0?"+":""}${ed} ponto(s) versus os 7 registros anteriores.`}</p></div></div>`}
function daily(){let d=S.daily.find(x=>x.date===today())||{};return`<div class=card><h3>Check-in de hoje</h3><form data-form=daily><div class=form>${[["energy","Energia"],["mood","Humor"],["stress","Estresse"],["focus","Foco"]].map(([n,l])=>`<div class=field><label>${l} · 1–5</label>${rate(n,d[n]||3)}</div>`).join("")}<div class="field full"><label>O que marcou seu dia?</label><textarea name=notes rows=4>${esc(d.notes)}</textarea></div></div><div class=actions><button>Salvar</button></div></form></div><h2 class=section>Histórico</h2><div class=list>${S.daily.slice(0,30).map(x=>`<div class=row><div><strong>${x.date}</strong><small>Energia ${x.energy}/5 · Humor ${x.mood}/5 · Foco ${x.focus}/5 · Estresse ${x.stress}/5</small></div><button class=danger data-del=daily_entries data-id="${x.id}">Excluir</button></div>`).join("")||"<p class=muted>Nenhum registro.</p>"}</div>`}
function sleep(){let d=S.sleep.find(x=>x.date===today())||{};return`<div class=card><h3>Registrar sono</h3><form data-form=sleep><div class=form><div class=field><label>Data</label><input type=date name=date value="${d.date||today()}" required></div><div class=field><label>Dormi</label><input type=time name=bed_time value="${d.bed_time||""}" required></div><div class=field><label>Acordei</label><input type=time name=wake_time value="${d.wake_time||""}" required></div><div class=field><label>Qualidade</label>${rate("quality",d.quality||3)}</div><div class=field><label>Despertares</label><input type=number min=0 name=awakenings value="${d.awakenings||0}"></div><div class="field full"><label>Notas</label><textarea name=notes>${esc(d.notes)}</textarea></div></div><div class=actions><button>Salvar</button></div></form></div><h2 class=section>Últimas noites</h2><div class=list>${S.sleep.slice(0,14).map(x=>`<div class=row><div><strong>${x.date} · ${hours(x).toFixed(1)}h</strong><small>Qualidade ${x.quality}/5 · ${x.awakenings||0} despertar(es)</small></div><button class=danger data-del=sleep_entries data-id="${x.id}">Excluir</button></div>`).join("")}</div>`}
function habits(){let a=S.habits.filter(x=>x.active);return`<div class=card><h3>Novo hábito</h3><form data-form=habit><div class=field><label>Nome</label><input name=name placeholder="Ex.: Caminhar 30 minutos" required></div><div class=actions><button>Adicionar</button></div></form></div><h2 class=section>Hoje</h2><div class=list>${a.map(h=>{let l=S.habit_logs.find(x=>x.habit_id===h.id&&x.date===today()&&x.completed),n=S.habit_logs.filter(x=>x.habit_id===h.id&&x.completed).length;return`<div class=row><div><strong>${esc(h.name)}</strong><small>${n} conclusão(ões)</small></div><div><button class="${l?"":"light"}" data-toggle="${h.id}">${l?"Concluído ✓":"Marcar"}</button> <button class=danger data-del=habits data-id="${h.id}">Excluir</button></div></div>`}).join("")||"<p class=muted>Crie seu primeiro hábito personalizado.</p>"}</div>`}
function books(){return`<div class=card><h3>Adicionar livro</h3><form data-form=book><div class=form><div class=field><label>Título</label><input name=title required></div><div class=field><label>Autor</label><input name=author></div><div class=field><label>Status</label><select name=status><option>Quero ler</option><option>Em andamento</option><option>Lido</option></select></div><div class=field><label>Total de páginas</label><input type=number min=0 name=pages></div><div class=field><label>Página atual</label><input type=number min=0 name=current_page></div><div class=field><label>Nota</label>${rate("rating",3)}</div><div class="field full"><label>Aprendizado</label><textarea name=notes></textarea></div><div class="field full"><label>O que quero aplicar</label><textarea name=application></textarea></div></div><div class=actions><button>Adicionar</button></div></form></div><h2 class=section>Biblioteca</h2><div class=list>${S.books.map(b=>{let pc=b.pages?Math.min(100,Math.round((b.current_page||0)/b.pages*100)):0;return`<div class=card><strong>${esc(b.title)}</strong><small>${esc(b.author)} · ${esc(b.status)} · ${pc}%</small><div class=progress><span style="width:${pc}%"></span></div><div class=actions><button class=danger data-del=books data-id="${b.id}">Excluir</button></div></div>`}).join("")}</div>`}
function studies(){return`<div class=card><h3>Registrar estudo</h3><form data-form=study><div class=form><div class=field><label>Data</label><input type=date name=date value="${today()}" required></div><div class=field><label>Assunto</label><input name=subject required></div><div class=field><label>Minutos</label><input type=number min=1 name=minutes required></div><div class="field full"><label>O que aprendi?</label><textarea name=learned></textarea></div></div><div class=actions><button>Salvar</button></div></form></div><h2 class=section>Histórico</h2><div class=list>${S.studies.map(x=>`<div class=row><div><strong>${esc(x.subject)}</strong><small>${x.date} · ${x.minutes} min</small></div><button class=danger data-del=studies data-id="${x.id}">Excluir</button></div>`).join("")}</div>`}
function goals(){return`<div class=card><h3>Novo objetivo</h3><form data-form=goal><div class=form><div class=field><label>Objetivo</label><input name=title required></div><div class=field><label>Prazo</label><input type=date name=deadline></div><div class=field><label>Progresso %</label><input type=number min=0 max=100 name=progress value=0></div><div class="field full"><label>Notas</label><textarea name=notes></textarea></div></div><div class=actions><button>Adicionar</button></div></form></div><h2 class=section>Objetivos</h2><div class=list>${S.goals.map(g=>`<div class=card><strong>${esc(g.title)}</strong><small>${g.deadline?"Prazo "+g.deadline:"Sem prazo"} · ${g.progress}%</small><div class=progress><span style="width:${g.progress}%"></span></div><div class=actions><button class=danger data-del=goals data-id="${g.id}">Excluir</button></div></div>`).join("")}</div>`}
function analysis(){let d=S.daily.slice(0,30),s=S.sleep.slice(0,30);return`<div class="grid stats">${[["Dias registrados",d.length],["Sono médio",s.length?avg(s.map(hours))+"h":"—"],["Humor médio",d.length?avg(d.map(x=>x.mood))+"/5":"—"],["Estudo total",S.studies.reduce((a,x)=>a+(+x.minutes||0),0)+" min"]].map(x=>`<div class=card><small>${x[0]}</small><div class=metric>${x[1]}</div></div>`).join("")}</div><div class=card style="margin-top:14px"><h3>Análises futuras</h3><p class=muted>Quando houver histórico suficiente, esta área poderá comparar sono, energia, foco, humor e hábitos sem tratar associação como causalidade.</p></div>`}
function render(){let name=Object.fromEntries(V)[S.view];$("#title").textContent=name;document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.go===S.view));$("#view").innerHTML=({dashboard,daily,sleep,habits,books,studies,goals,analysis}[S.view])()}
document.addEventListener("click",async e=>{let g=e.target.closest("[data-go]");if(g){S.view=g.dataset.go;render()}let r=e.target.closest("[data-rate]");if(r){document.querySelectorAll(`[data-rate="${r.dataset.rate}"]`).forEach(x=>x.classList.remove("on"));r.classList.add("on");document.querySelector(`[name="${r.dataset.rate}"]`).value=r.dataset.v}let d=e.target.closest("[data-del]");if(d)await del(d.dataset.del,d.dataset.id);let t=e.target.closest("[data-toggle]");if(t){let l=S.habit_logs.find(x=>x.habit_id===t.dataset.toggle&&x.date===today());l?await del("habit_logs",l.id):await add("habit_logs",{habit_id:t.dataset.toggle,date:today(),completed:true})}})
document.addEventListener("submit",async e=>{let f=e.target.closest("[data-form]");if(!f)return;e.preventDefault();let x=Object.fromEntries(new FormData(f)),t=f.dataset.form;if(t==="daily"){["energy","mood","stress","focus"].forEach(k=>x[k]=+x[k]);x.date=today();await up("daily_entries",x)}if(t==="sleep"){x.quality=+x.quality;x.awakenings=+x.awakenings;await up("sleep_entries",x)}if(t==="habit")await add("habits",{name:x.name.trim(),active:true});if(t==="book"){x.pages=+x.pages||0;x.current_page=+x.current_page||0;x.rating=+x.rating;await add("books",x)}if(t==="study"){x.minutes=+x.minutes;await add("studies",x)}if(t==="goal"){x.progress=+x.progress||0;x.date=today();await add("goals",x)}})
$("#login").onclick=async()=>{if(!sb)return $("#msg").textContent="Configure o config.js.";let{error}=await sb.auth.signInWithPassword({email:$("#email").value,password:$("#password").value});if(error)$("#msg").textContent=error.message}
$("#signup").onclick=async()=>{if(!sb)return $("#msg").textContent="Configure o config.js.";let{error}=await sb.auth.signUp({email:$("#email").value,password:$("#password").value});$("#msg").textContent=error?error.message:"Conta criada. Verifique seu e-mail se a confirmação estiver ativa."}
$("#logout").onclick=()=>sb?.auth.signOut();$("#export").onclick=()=>{let b=new Blob([JSON.stringify({...S,user:undefined},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=`greene-backup-${today()}.json`;a.click()}
if(sb)sb.auth.onAuthStateChange(async(_,s)=>{S.user=s?.user||null;$("#auth").classList.toggle("hidden",!!S.user);$("#app").classList.toggle("hidden",!S.user);if(S.user){await load();render()}});